### ISSUE TITLE
game crashes on launch

### ISSUE THREAD

**Issue by Ragemachine771** [Quarris/VoidTanks#2]
[crash-2021-09-23_09.20.04-fml.txt](https://github.com/Quarris/VoidTanks/files/7217955/crash-2021-09-23_09.20.04-fml.txt)
![image](https://user-images.githubusercontent.com/91267651/134515179-b0ea8148-817e-41b4-8943-f374ff8942c0.png)
[latest.log](https://github.com/Quarris/VoidTanks/files/7217965/latest.log)

**Comment by Ragemachine771** [comment]
my mods list
![image](https://user-images.githubusercontent.com/91267651/134515421-f6a8901a-db5b-4b21-b8ff-f2c1b4b92784.png)
 and im running version 1.17.1

**Comment by Quarris** [comment]
This is using more recent version of forge. I will update when I have time

**Comment by Ragemachine771** [comment]
appreciated, if you need any testing done just ask :)
